"Resource/UI/SpectatorGUI.res"
{
	"SpectatorGUI"
	{
		"ControlName"	"Frame"
		"fieldName"		"SpectatorGUI"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"640"
		"tall"			"480"
		"visible"		"1"
		"enabled"		"1"
		"paintbackground" "0"
	}
	"topbar"
	{
		"ControlName"	"Panel"
		"fieldName"		"topbar"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"1"
		"tall"			"1"
		"visible"		"0"
		"enabled"		"0"
		"paintbackground" "0"
	}
	"bottombarblank"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"bottombarblank"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"288"
		"tall"			"46"
		"visible"		"0"
		"enabled"		"1"
		"paintbackground" "1"
		"bgcolor_override" "18 19 18 238"
		"zpos"			"1"
		"cardcenter"
		{
			"ControlName"	"Panel"
			"fieldName"		"cardcenter"
			"xpos"			"64"
			"ypos"			"2"
			"wide"			"160"
			"tall"			"44"
			"visible"		"1"
			"paintbackground" "1"
			"bgcolor_override" "28 30 29 246"
			"zpos"			"0"
		}
		"cardaccent"
		{
			"ControlName"	"Panel"
			"fieldName"		"cardaccent"
			"xpos"			"0"
			"ypos"			"0"
			"wide"			"288"
			"tall"			"2"
			"visible"		"1"
			"paintbackground" "1"
			"bgcolor_override" "232 112 32 255"
			"zpos"			"3"
		}
		"leftdivider"
		{
			"ControlName"	"Panel"
			"fieldName"		"leftdivider"
			"xpos"			"64"
			"ypos"			"2"
			"wide"			"1"
			"tall"			"44"
			"visible"		"1"
			"paintbackground" "1"
			"bgcolor_override" "92 88 78 190"
			"zpos"			"2"
		}
		"rightdivider"
		{
			"ControlName"	"Panel"
			"fieldName"		"rightdivider"
			"xpos"			"223"
			"ypos"			"2"
			"wide"			"1"
			"tall"			"44"
			"visible"		"1"
			"paintbackground" "1"
			"bgcolor_override" "92 88 78 190"
			"zpos"			"2"
		}
		"healthcaption"
		{
			"ControlName"	"Label"
			"fieldName"		"healthcaption"
			"xpos"			"0"
			"ypos"			"3"
			"wide"			"64"
			"tall"			"8"
			"font"			"DefaultSmall"
			"fgcolor_override" "232 112 32 255"
			"labelText"		"HEALTH"
			"textAlignment" "center"
			"visible"		"1"
			"zpos"			"2"
		}
		"healthvalue"
		{
			"ControlName"	"Label"
			"fieldName"		"healthvalue"
			"xpos"			"0"
			"ypos"			"9"
			"wide"			"64"
			"tall"			"25"
			"font"			"HudNumbersSmall"
			"fgcolor_override" "232 232 226 255"
			"labelText"		"100"
			"textAlignment" "center"
			"visible"		"1"
			"zpos"			"2"
		}
		"armorvalue"
		{
			"ControlName"	"Label"
			"fieldName"		"armorvalue"
			"xpos"			"0"
			"ypos"			"34"
			"wide"			"64"
			"tall"			"9"
			"font"			"DefaultSmall"
			"fgcolor_override" "174 176 170 255"
			"labelText"		"SUIT 0"
			"textAlignment" "center"
			"visible"		"1"
			"zpos"			"2"
		}
		"modelabel"
		{
			"ControlName"	"Label"
			"fieldName"		"modelabel"
			"xpos"			"64"
			"ypos"			"3"
			"wide"			"160"
			"tall"			"8"
			"font"			"DefaultSmall"
			"fgcolor_override" "232 112 32 255"
			"labelText"		""
			"textAlignment" "center"
			"visible"		"1"
			"zpos"			"2"
		}
		"playerlabel"
		{
			"ControlName"	"Label"
			"fieldName"		"playerlabel"
			"xpos"			"64"
			"ypos"			"10"
			"wide"			"160"
			"tall"			"14"
			"font"			"Default"
			"fgcolor_override" "232 232 226 255"
			"labelText"		""
			"textAlignment" "center"
			"visible"		"1"
			"zpos"			"2"
		}
		"weaponlabel"
		{
			"ControlName"	"Label"
			"fieldName"		"weaponlabel"
			"xpos"			"64"
			"ypos"			"23"
			"wide"			"160"
			"tall"			"10"
			"font"			"DefaultSmall"
			"fgcolor_override" "174 176 170 255"
			"labelText"		""
			"textAlignment" "center"
			"visible"		"1"
			"zpos"			"2"
		}
		"auxcaption"
		{
			"ControlName"	"Label"
			"fieldName"		"auxcaption"
			"xpos"			"71"
			"ypos"			"35"
			"wide"			"19"
			"tall"			"8"
			"font"			"DefaultSmall"
			"fgcolor_override" "174 176 170 255"
			"labelText"		"AUX"
			"textAlignment" "west"
			"visible"		"1"
			"zpos"			"2"
		}
		"auxpowertrack"
		{
			"ControlName"	"Panel"
			"fieldName"		"auxpowertrack"
			"xpos"			"93"
			"ypos"			"38"
			"wide"			"124"
			"tall"			"2"
			"visible"		"1"
			"paintbackground" "1"
			"bgcolor_override" "86 84 78 190"
			"zpos"			"2"
			"auxpowerfill"
			{
				"ControlName"	"Panel"
				"fieldName"		"auxpowerfill"
				"xpos"			"0"
				"ypos"			"0"
				"wide"			"124"
				"tall"			"2"
				"visible"		"1"
				"paintbackground" "1"
				"bgcolor_override" "232 112 32 255"
				"zpos"			"1"
			}
		}
		"ammocaption"
		{
			"ControlName"	"Label"
			"fieldName"		"ammocaption"
			"xpos"			"224"
			"ypos"			"3"
			"wide"			"64"
			"tall"			"8"
			"font"			"DefaultSmall"
			"fgcolor_override" "232 112 32 255"
			"labelText"		"AMMO"
			"textAlignment" "center"
			"visible"		"1"
			"zpos"			"2"
		}
		"ammovalue"
		{
			"ControlName"	"Label"
			"fieldName"		"ammovalue"
			"xpos"			"224"
			"ypos"			"9"
			"wide"			"64"
			"tall"			"25"
			"font"			"HudNumbersSmall"
			"fgcolor_override" "232 232 226 255"
			"labelText"		"30"
			"textAlignment" "center"
			"visible"		"1"
			"zpos"			"2"
		}
		"reservevalue"
		{
			"ControlName"	"Label"
			"fieldName"		"reservevalue"
			"xpos"			"224"
			"ypos"			"34"
			"wide"			"64"
			"tall"			"9"
			"font"			"DefaultSmall"
			"fgcolor_override" "174 176 170 255"
			"labelText"		"R:90"
			"textAlignment" "center"
			"visible"		"1"
			"zpos"			"2"
		}
	}
	"observerpanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"observerpanel"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"204"
		"tall"			"18"
		"visible"		"0"
		"enabled"		"1"
		"paintbackground" "1"
		"bgcolor_override" "18 19 18 222"
		"zpos"			"1"
		"observeraccent"
		{
			"ControlName"	"Panel"
			"fieldName"		"observeraccent"
			"xpos"			"0"
			"ypos"			"0"
			"wide"			"204"
			"tall"			"2"
			"visible"		"1"
			"paintbackground" "1"
			"bgcolor_override" "232 112 32 255"
			"zpos"			"2"
		}
		"observermode"
		{
			"ControlName"	"Label"
			"fieldName"		"observermode"
			"xpos"			"7"
			"ypos"			"2"
			"wide"			"68"
			"tall"			"16"
			"font"			"DefaultSmall"
			"fgcolor_override" "232 112 32 255"
			"labelText"		"OBSERVER"
			"textAlignment" "west"
			"visible"		"1"
			"zpos"			"2"
		}
		"observerhint"
		{
			"ControlName"	"Label"
			"fieldName"		"observerhint"
			"xpos"			"75"
			"ypos"			"2"
			"wide"			"122"
			"tall"			"16"
			"font"			"DefaultSmall"
			"fgcolor_override" "174 176 170 255"
			"labelText"		""
			"textAlignment" "east"
			"visible"		"1"
			"zpos"			"2"
		}
	}
}
